# =====================================================
# AI Knowledge Assistant - Application Configuration
# =====================================================

application:

llm:
  #provider: gemini
  #model: gemini-3.6-flash
  #temperature: 0
  provider: claude
  model: claude-sonnet-4-6
  temperature: 0
  

deepeval_judgellm:
  #provider: gemini
  #model: gemini-3.6-flash
  #temperature: 0
  provider: claude
  model: claude-sonnet-4-6
  temperature: 0
  #provider: groq
  #model: llama-3.1-8b-instant
  #temperature: 0

security:
  allowed_jira_projects:
    - REL

  authorized_jira_actions:
    - create
    - update

  authorized_task_assignees:
    - lavanya.bathina@gmail.com
    - lakumabathina@gmail.com

  authorized_parent_story_assignees:
    - lavanya.bathina@gmail.com

  allowed_confluence_spaces:
    - lavanya bathina